### ISSUE TITLE
Could not find donor npc

### ISSUE THREAD

**Issue by waterbottlestraw** [Piranha91/NPC-Appearance-Copier#7]
With some mods, the tool doesn't work and cites that it "Could not find donor NPC". The tool often works if the donor npc is from a script heavy mod, but fails with the ESL flagged ones mainly.

I tried removing the ESL flag, and installing some standalone followers without the ESL flag and it still fails to find the donor npc. Any idea on how to fix this?

**Comment by waterbottlestraw** [comment]
For anyone else having this issue, remember to have Synthesis loaded last in your load order. Stupid mistake, literally just dragged Synthesis down to the bottom and it worked

**Comment by Piranha91** [comment]
Yep, Synthesis ignores whatever is below its own esp. Glad you figured it out!
